gateway:
  # Valid protocols are currently http, tcp and tls
  service:
    type: ClusterIP
  podDisruptionBudget:
    minAvailable: 1
accessLog: true
port: 443
serviceEntryPerHost: false
resolution: DNS
protocol: tls
sidecar: true
ambient: false
# https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/
# tls-origination only works with protocol http
tls-origination: false
image:
  repository: 674851156463.dkr.ecr.eu-north-1.amazonaws.com/deniedboarding/egress
  tag: 3.1.2
