gateway:
  # Valid protocols are currently http, tcp and tls
  protocol: tls
  sidecar: true
  ambient: false
  service:
    type: ClusterIP
  podDisruptionBudget:
    minAvailable: 1
accessLog: true
port: 443
serviceEntryPerHost: false
resolution: DNS
image:
  repository: 674851156463.dkr.ecr.eu-north-1.amazonaws.com/deniedboarding/egress
  tag: 2.4.0
