gateway:
  # Valid protocols are currently http, tcp and tls
  service:
    type: ClusterIP
  podDisruptionBudget:
    minAvailable: 1
accessLog: true
port: 443
serviceEntryPerHost: false
resolution: DNS
protocol: tls
sidecar: true
ambient: false
