gateway:
  # Valid protocols are currently http and tls
  protocol: tls
  sidecar: true
  ambient: false
  service:
    type: ClusterIP
  podDisruptionBudget:
    minAvailable: 1
accessLog: true
port: 443
serviceEntryPerHost: false
