gateway:
  # Valid protocols are currently http, tcp and tls
  service:
    type: ClusterIP
  podDisruptionBudget:
    minAvailable: 1
  resources:
    requests:
      cpu: 25m
      memory: 75Mi
accessLog: true
port: 443
serviceEntryPerHost: false
resolution: DNS
protocol: tls
sidecar: true
gatewaySidecar: false
ambient: false
# https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/
# Enable TLS origination if protocol is tls
tlsOrigination: true
trafficPolicy:
  loadBalancer:
    simple: ROUND_ROBIN
portLevelSetting:
  connectionPool:
    http:
      idleTimeout: 5m
    tcp:
      idleTimeout: 5m
