{{ if .Values.sidecar }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: egressgateway-for-{{ include "name" . }}
spec:
  host: {{ .Values.gateway.name }}.istio-system.svc.cluster.local
  subsets:
  - name: {{ include "name" . }}
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 30s
      consecutive5xxErrors: 5
      interval: 10s
      maxEjectionPercent: 50
{{ end }}