{{ if .Values.sidecar }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: egressgateway-for-{{ include "name" . }}
  labels:
    {{- include "egress.labels" . | nindent 4}}
spec:
  host: {{ .Values.gateway.name }}.istio-system.svc.cluster.local
  subsets:
  - name: {{ include "name" . }}
{{ if and .Values.tlsOrigination (eq .Values.protocol "tls") }}
{{ range .Values.hosts }}
  - name: {{ . | replace "." "-"  }}-tls-origination
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: ISTIO_MUTUAL
          sni: {{ . }}
{{ end }}
{{ end }}
  trafficPolicy:
    outlierDetection:
      baseEjectionTime: 30s
      consecutive5xxErrors: 5
      interval: 10s
      maxEjectionPercent: 50
{{ end }}
