apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    istio: {{ .Values.gateway.name }}
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - {{ .Values.host }}
    tls:
      mode: PASSTHROUGH
