apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    istio: {{ .Values.gateway.name }}
  servers:
  - port:
      number: {{ .Values.port }}
      name: tls
      protocol: TLS
    hosts: {{ toYaml .Values.hosts | nindent 4 }}
    tls:
      mode: PASSTHROUGH
