apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    istio: {{ .Values.gateway.name }}
  servers:
  - port:
      number: {{ .Values.port }}
      name: tls
      protocol: TLS
{{ with .Values.hosts }}
    hosts: {{ toYaml . | nindent 4 }}
{{ end }}
    tls:
      mode: PASSTHROUGH
