{{ if .Values.sidecar }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  labels:
    {{- include "egress.labels" . | nindent 4}}
spec:
  selector:
    istio: {{ .Values.gateway.name }}
  servers:
  - port:
      number: {{ .Values.port }}
      name: {{ .Values.protocol }}
      protocol: {{ .Values.protocol | upper }}
{{ with .Values.hosts }}
    hosts: {{ toYaml . | nindent 4 }}
{{ end }}
{{ if and .Values.tlsOrigination (eq .Values.protocol "tls") }}
    tls:
      mode: PASSTHROUGH
  - port:
      name: https-port-for-tls-origination
      number: 80
      protocol: HTTPS
{{ with .Values.hosts }}
    hosts: {{ toYaml . | nindent 4 }}
{{ end }}
    tls:
      mode: ISTIO_MUTUAL
{{ end }}
{{ end }}