{{ if .Values.sidecar }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  labels:
    {{- include "egress.labels" . | nindent 4}}
spec:
  selector:
    istio: {{ .Values.gateway.name }}
  servers:
  - port:
      number: {{ .Values.port }}
      name: {{ .Values.protocol }}
      protocol: {{ .Values.protocol | upper }}
    hosts: {{ toYaml .Values.hosts | nindent 4 }}
{{ if and .Values.tlsOrigination (eq .Values.protocol "tls") }}
    tls:
      mode: PASSTHROUGH
  - hosts: {{ toYaml .Values.hosts | nindent 4 }}
    - edition.cnn.com
    port:
      name: http-port-for-tls-origination
      number: 80
      protocol: HTTP
{{ end }}
{{ end }}