{{- $seScope := deepCopy . -}}
{{ if .Values.serviceEntryPerHost }}
{{ range .Values.hosts }}
{{- $_ := set $seScope "hosts" (list .) -}}
{{- $_ = set $seScope "name" (trimPrefix "*." .) -}}
{{- include "egress.service-entry" $seScope }}
---
{{ end }}
{{ else }}
{{- $_ := set $seScope "hosts" .Values.hosts -}}
{{- $_ = set $seScope "name" (include "name" $seScope) -}}
{{- include "egress.service-entry" $seScope }}
{{ end }}
