apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ include "name" . }}
spec:
  hosts:
  - {{ .Values.host }}
  ports:
  - number: {{ .Values.port }}
    name: tls
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
