apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ include "name" . }}
spec:
{{ with .Values.hosts }}
  hosts: {{ toYaml . | nindent 2 }}
{{ end }}
  ports:
  - number: {{ .Values.port }}
    name: tls
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
