apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ include "name" . }}
spec:
  hosts:  {{ toYaml .Values.hosts | nindent 2 }}
  ports:
  - number: {{ .Values.port }}
    name: tls
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
