{{ if .Values.accessLog -}}
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "egress.labels" . | nindent 4}}
spec:
  accessLogging:
  - providers:
    - name: envoy
  selector:
    matchLabels:
      app: {{ .Values.gateway.name }}
{{ end -}}
