apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: direct-{{ include "name" . }}-through-egress-gateway
spec:
{{ with .Values.hosts }}
    hosts: {{ toYaml . | nindent 2 }}
{{ end }}
  gateways:
  - mesh
  - {{ .Values.gateway.name }}
  tls:
  - match:
    - gateways:
      - mesh
      port: {{ .Values.port }}
{{ with .Values.hosts }}
      sniHosts: {{ toYaml . | nindent 6 }}
{{ end }}
    route:
    - destination:
        host: {{ .Values.gateway.name }}.istio-system.svc.cluster.local
        subset: {{ include "name" . }}
        port:
          number: {{ .Values.port }}
  - match:
{{ range .Values.hosts }}
    - gateways:
      - {{ $.Values.gateway.name }}
      port: {{ $.Values.port }}
      sniHosts:
      - {{ . }}
    route:
    - destination:
        host: {{ . }}
        port:
          number: {{ $.Values.port }}
      weight: 100
{{ end }}