{{ if .Values.sidecar }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: direct-{{ include "name" . }}-through-egress-gateway
  labels:
    {{- include "egress.labels" . | nindent 4}}
spec:
{{ with .Values.hosts }}
  hosts: {{ toYaml . | nindent 2 }}
{{ end }}
  gateways:
  - mesh
  - {{ .Values.gateway.name }}
  {{ .Values.protocol }}:
  - match:
    - gateways:
      - mesh
      port: {{ .Values.port }}
{{ if eq .Values.protocol "tls" }}
{{ with .Values.hosts }}
      sniHosts: {{ toYaml . | nindent 6 }}
{{ end }}
{{ end }}
    route:
    - destination:
        host: {{ .Values.gateway.name }}.istio-system.svc.cluster.local
        subset: {{ include "name" . }}
        port:
          number: {{ .Values.port }}
{{ range .Values.hosts }}
  - match:
    - gateways:
      - {{ $.Values.gateway.name }}
      port: {{ $.Values.port }}
{{ if eq $.Values.protocol "tls" }}
      sniHosts:
      - {{ . | quote }}
{{ else if eq $.Values.protocol "http" }}
      authority: {{- include "egress.string-match" . | nindent 8 }}
{{ end }}
    route:
    - destination:
        host: {{ . | quote }}
{{ if and $.Values.tlsOrigination (eq $.Values.protocol "tls") }}
        subset: {{ include "name" $ }}
{{ end }}
        port:
          number: {{ $.Values.port }}
      weight: 100
{{ end }}
{{ if and .Values.tlsOrigination (eq .Values.protocol "tls") }}
  http:
{{ range .Values.hosts }}
  - match:
    - gateways:
      - mesh
      port: 80
      authority: {{- include "egress.string-match" . | nindent 8 }}
    route:
    - destination:
        host: {{ $.Values.gateway.name }}.istio-system.svc.cluster.local
        subset: {{ . | trimPrefix "*." | replace "." "-" }}-tls-origination
        port:
          number: 80
  - match:
    - gateways:
      - {{ $.Values.gateway.name }}
      port: 80
      authority: {{- include "egress.string-match" . | nindent 8 }}
    route:
    - destination:
        host: {{ . | quote }}
        subset: tls-origination
        port:
          number: {{ $.Values.port }}
      weight: 100
{{ end }}
{{ end }}
{{ end }}